package io.scenariomesh.maven.extension;

import org.apache.maven.model.Plugin;
import org.apache.maven.model.PluginExecution;
import org.codehaus.plexus.util.xml.Xpp3Dom;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SurefireSelectionFileCompatibilityTest {
    private final SurefireCompatibility compatibility = new SurefireCompatibility();

    @TempDir
    Path projectDir;

    @Test
    void appendsIncludesFilePatternsToInlineIncludesAndIgnoresComments() throws IOException {
        Files.writeString(projectDir.resolve("surefire-includes.txt"), "# generated by build\n\n**/*ContractTest.java\n");

        Plugin plugin = plugin();
        Xpp3Dom configuration = new Xpp3Dom("configuration");
        Xpp3Dom includes = new Xpp3Dom("includes");
        add(includes, "include", "**/*SmokeTest.java");
        configuration.addChild(includes);
        add(configuration, "includesFile", "surefire-includes.txt");
        plugin.setConfiguration(configuration);

        SurefireCompatibility.Analysis analysis = compatibility.analyze(
                plugin, Map.of("project.basedir", projectDir.toString())::get);

        assertTrue(analysis.reasons().isEmpty(), () -> String.join("; ", analysis.reasons()));
        assertTrue(matches(analysis, "example/CheckoutSmokeTest.class"));
        assertTrue(matches(analysis, "example/CheckoutContractTest.class"));
        assertFalse(matches(analysis, "example/CheckoutTest.class"));
    }

    @Test
    void appendsExcludesFilePatternsToInlineExcludes() throws IOException {
        Files.writeString(projectDir.resolve("surefire-excludes.txt"), "**/*FlakyTest.java\n");

        Plugin plugin = plugin();
        Xpp3Dom configuration = new Xpp3Dom("configuration");
        Xpp3Dom excludes = new Xpp3Dom("excludes");
        add(excludes, "exclude", "**/*SlowTest.java");
        configuration.addChild(excludes);
        add(configuration, "excludesFile", "surefire-excludes.txt");
        plugin.setConfiguration(configuration);

        SurefireCompatibility.Analysis analysis = compatibility.analyze(
                plugin, Map.of("project.basedir", projectDir.toString())::get);

        assertTrue(analysis.reasons().isEmpty(), () -> String.join("; ", analysis.reasons()));
        assertTrue(matchesExclude(analysis, "example/CheckoutSlowTest.class"));
        assertTrue(matchesExclude(analysis, "example/CheckoutFlakyTest.class"));
    }

    @Test
    void methodSelectorInIncludesFileFailsClosed() throws IOException {
        Files.writeString(projectDir.resolve("surefire-includes.txt"), "example.LoginTest#smoke\n");

        Plugin plugin = plugin();
        plugin.setConfiguration(configuration("includesFile", "surefire-includes.txt"));

        SurefireCompatibility.Analysis analysis = compatibility.analyze(
                plugin, Map.of("project.basedir", projectDir.toString())::get);

        assertTrue(analysis.reasons().stream().anyMatch(reason -> reason.contains("method selectors")),
                () -> String.join("; ", analysis.reasons()));
    }

    @Test
    void missingSelectionFileFailsClosed() {
        Plugin plugin = plugin();
        plugin.setConfiguration(configuration("includesFile", "missing-tests.txt"));

        SurefireCompatibility.Analysis analysis = compatibility.analyze(
                plugin, Map.of("project.basedir", projectDir.toString())::get);

        assertTrue(analysis.reasons().stream().anyMatch(reason -> reason.contains("readable regular file")),
                () -> String.join("; ", analysis.reasons()));
    }

    private boolean matches(SurefireCompatibility.Analysis analysis, String classFilePath) {
        return analysis.includeClassNameRegexes().stream().anyMatch(regex -> Pattern.matches(regex, classFilePath));
    }

    private boolean matchesExclude(SurefireCompatibility.Analysis analysis, String classFilePath) {
        return analysis.excludeClassNameRegexes().stream().anyMatch(regex -> Pattern.matches(regex, classFilePath));
    }

    private Plugin plugin() {
        Plugin plugin = new Plugin();
        plugin.setGroupId("org.apache.maven.plugins");
        plugin.setArtifactId("maven-surefire-plugin");
        PluginExecution execution = new PluginExecution();
        execution.setId("default-test");
        execution.setPhase("test");
        execution.addGoal("test");
        plugin.addExecution(execution);
        return plugin;
    }

    private Xpp3Dom configuration(String name, String value) {
        Xpp3Dom root = new Xpp3Dom("configuration");
        add(root, name, value);
        return root;
    }

    private void add(Xpp3Dom root, String name, String value) {
        Xpp3Dom child = new Xpp3Dom(name);
        child.setValue(value);
        root.addChild(child);
    }
}
