<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>example</groupId><artifactId>dependencies-to-scan-example</artifactId><version>1.0-SNAPSHOT</version></parent><artifactId>dependency-tests</artifactId><properties><maven.compiler.release>17</maven.compiler.release></properties><dependencies><dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><version>5.10.5</version><scope>test</scope></dependency></dependencies><build><plugins><plugin><artifactId>maven-jar-plugin</artifactId><version>3.4.2</version><executions><execution><goals><goal>test-jar</goal></goals></execution></executions></plugin></plugins></build></project>
